mybatis:
  mapperLocations: classpath:mybatis/*-mapper.xml
  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: moe.studio.spring.boot
  checkConfigLocation: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jpa?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false